# Generated by Django 4.1.2 on 2023-06-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=10)),
            ],
        ),
    ]
